### ISSUE TITLE
Hacktoberfest: Add GIF to showcase gistup

### ISSUE THREAD

**Issue by tuladhar** [tuladhar/gistup#1]
# Hacktoberfest: Add GIF to showcase gistup

### Acceptance Criteria
- Create a GIF demonstrating how gistup works. **(Difficulties: Easy)**
- GIF should be at least 800x600px 

**NOTE:**
- You are new to terminal recording or creating GIF, here's some resources to get started:
   - [GIPHY](https://giphy.com/)
   - [TermRecord](https://pypi.org/project/TermRecord/)
   -  [See here for List of terminal recording tools for Linux](https://linoxide.com/linux-how-to/linux-terminal-recording-tools/)
   - [Record terminal sessions using GIFY Capture or Asciinema](https://techsparx.com/blog/2019/08/terminal-recording.html)
   - [Terminalizer](https://terminalizer.com/)

- - -
Stay Safe & Happy Hacking,
Puru

**Comment by Ryuno-Ki** [comment]
This code wasn't touched in four years.
Is it still eligble for Hacktoberfest?

The recording could happen using [TermRecord](https://pypi.org/project/TermRecord/) or another [terminal recording tool](https://linoxide.com/linux-how-to/linux-terminal-recording-tools/).

People even figured out [how to record terminal using a script inside Docker](https://techsparx.com/blog/2019/08/terminal-recording.html).

If Node.js would be an option, there are more possibilities, e.g. [Terminalizer](https://terminalizer.com/).

**Comment by tuladhar** [comment]
@Ryuno-Ki As far as I'm aware, there's no age limit for the repository. So, yes it's eligible. Basically, the theme here is to welcome new contributors to open-source and contribute.

 Thanks for the list, I'll add those to the description as well.

**Comment by liisberg** [comment]
I can do this, please assign it to me.

Will update the code to run on python3 aswell!

**Comment by tuladhar** [comment]
Thanks @liisberg. Assigned.

**Comment by Ryuno-Ki** [comment]
@tuladhar Hm, looks like I wasn't expressive enough.

I was wondering, why a seemingly dead (=> no updates) repository should get pull requests.
This year, DigitalOcean has to fight with spamming more than ever.

But it's good to see repositories revived. So go for it!
